docs: add Admin API samples for account management methods
googleapis/python-analytics-admin pull request #65
Opened 2021-05-19 20:54 UTC by ikuleshov

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-analytics-admin/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

2021-05-19 22:03 UTC, ikuleshov commented
Region tag product prefix check is failing due to the product set as non-public in https://devrel.corp.google.com/admin/products/401. This is something that we are currently working on, but I believe the region prefixes are fine.

2021-05-25 20:05 UTC, diminishedprime approved these changes

2021-05-27 22:18 UTC, leahecole requested changes
I stopped about halfway through because it was going to be obnoxious to see me say "same as above" on the tests - the samples themselves look great as far as I can tell, and the tests aren't bad as is (they're independent of each other and valid! Woo!), but I think they could be hardened with the use of fixtures. If you need it, this [cloud storage test](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/storage/cloud-client/snippets_test.py) has some examples of function scoped fixtures and crud operations

2021-05-27 22:18 UTC, leahecole commented on samples/accounts_user_links_audit_test.py
> +    assert "Result" in out
It would probably make sense to add a few more asserts for your other print statements just to be super sure they happen

2021-05-27 22:18 UTC, leahecole commented on samples/accounts_user_links_batch_create_test.py
> +def test_accounts_user_links_batch_create():
Is there a way to test the happy path and delete it afterwards with a fixture? I do like the creative 403 as an additional test

2021-05-27 22:18 UTC, leahecole commented on samples/accounts_user_links_batch_delete.py
> +    #  Running this sample may change/delete your Google Analytics account
love this very helpful comment A+ DevX it caught my attention immediately

2021-05-27 22:18 UTC, leahecole commented on samples/accounts_user_links_batch_delete_test.py
> +def test_accounts_user_links_batch_delete():
similar to the create, would love to see a test that uses a fixture to create then actually deletes and checks to see that the value is no longer there

2021-05-27 22:18 UTC, leahecole commented on samples/accounts_user_links_batch_get_test.py
> +    assert "Result" in out
is the value you're expecting known? Could you add more to this assert if it's the same test value you're looking for every time? 

(Should you add a value in a fixture that you then "get" in the test and delete in the teardown?)

2021-05-27 22:18 UTC, leahecole commented on samples/accounts_user_links_batch_update_test.py
> +def test_accounts_user_links_batch_update():
Same as others - would love to see a fake account that gets created and deleted in a fixture and updated in the test

2021-05-27 23:42 UTC, ikuleshov commented
Leah, to address comments above. Problem is, it is currently impossible to create a new Google Analytics account programmatically using a public API due to the need for a user to accept Terms of Services. The feature to provision a new account automatically will likely be implemented by end of Q3, so we might be able to do more interesting tests. Right now, I would prefer to not mutate the state of the test GA account since there is no easy way to reset it to the original state in case something goes wrong. As a result, the tests mainly check for the validity of the request proto for now.

2021-05-27 23:47 UTC, leahecole approved these changes

2021-05-27 23:50 UTC, merged